server:
  port: ${PORT:8080}


spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter:
                      replenishRate: 50
                      burstCapacity: 100
                      requestedTokens: 5
                    key-resolver: "#{@ipKeyResolver}"
            - id: patient-service
              uri: lb://patient-service
              predicates:
                - Path=/api/v1/patients/**
              filters:
                - name: JwtAuth
                  args:
                    ROLE: [ PATIENT ]
                    GET: [ ADMIN_READ ]
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter:
                      replenishRate: 50
                      burstCapacity: 100
                      requestedTokens: 5
                    key-resolver: "#{@ipKeyResolver}"
                - name: Retry
                  args:
                    retries: 3
                    statuses: BAD_GATEWAY
                    methods: GET, POST
                    backoff:
                      firstBackoff: 10ms
                      maxBackoff: 50ms
                      factor: 2
                      basedOnPreviousValue: false
                    timeout: 100ms
                - name: CircuitBreaker
                  args:
                    name: patientCircuitBreaker
                    fallbackUri: forward:/fallback/patients
  data:
    redis:
      host: ${REDIS_Host:localhost}
      port: ${REDIS_PORT:6379}

# Config Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      patientCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
jwt:
  public:
    public-key-path: ${JWT_KEY_PEM_PATH:keys/public.pem}
  ttl: 300000
springdoc:
  swagger-ui:
    urls:
      - name: gateway
        url: http://localhost:8080/v3/api-docs
      - name: auth-service
        url: http://localhost:8090/v3/api-docs
      - name: patient-service
        url: http://localhost:8091/v3/api-docs
    path: /swagger-ui.html
    urls-primary-name: auth-service
    deep-linking: true
  api-docs:
    path: /v3/api-docs
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0  # 100% trace để test
    exporter:
      zipkin:
        enabled: true
        endpoint: http://localhost:9411/api/v2/spans  # Zipkin endpoint

  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    # === Gateway core: để biết route nào được chọn ===
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: DEBUG

    # === Gateway filter: log các filter xử lý request ===
    org.springframework.cloud.gateway.filter: DEBUG

    # === CircuitBreaker, Retry, RateLimit (nếu dùng) ===
    org.springframework.cloud.gateway.filter.factory.CircuitBreakerGatewayFilterFactory: DEBUG
    org.springframework.cloud.gateway.filter.factory.RetryGatewayFilterFactory: DEBUG
    org.springframework.cloud.gateway.filter.ratelimit: DEBUG

    # === Micrometer observation & tracing ===
    io.micrometer.tracing: DEBUG
    io.micrometer.observation: DEBUG

    # === Gateway Observation Filters (tự tạo span) ===
    org.springframework.cloud.gateway.observation: DEBUG
    org.springframework.cloud.gateway.observation.ObservedRequestHttpHeadersFilter: DEBUG

    # === Redis (nếu dùng để store rate/quota/token...) ===
    org.springframework.data.redis: DEBUG

    # === WebClient (nếu gọi downstream service) ===
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG

