server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: patient-service
              uri: lb://patient-service
              predicates:
                - Path=/api/v1/patients/**
              filters:
                - name: JwtAuth
                  args:
                    GET: [ ADMIN ]
                    POST: [ ADMIN ]
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
jwt:
  secret: 8b77d7fc7dc4fecb1cbe419e2b0512625e8cf3599fd8b141ec077c7a2e4d0459
