server:
  port: ${PORT:8092}

spring:
  messages:
    encoding: UTF-8
  application:
    name: doctor-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/clinic_patient}
    username: ${SPRING_DATASOURCE_USERNAME:clinic}
    password: ${SPRING_DATASOURCE_PASSWORD:clinic123}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:http://localhost:8888