server:
  port: 8080

spring:
  messages:
    encoding: UTF-8
  application:
    name: patient-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/clinic_patient}
    username: ${SPRING_DATASOURCE_USERNAME:clinic}
    password: ${SPRING_DATASOURCE_PASSWORD:clinic123}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://host.docker.internal:8761/eureka}
