input {
  beats {
    port => 5044
  }
}

filter {
}

output {
  stdout {
    codec => rubydebug
  }

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]

    data_stream => true
    data_stream_type => "logs"
    data_stream_dataset => "clinic-system-app-logs"
    data_stream_namespace => "default"  # Có thể đổi thành: %{[@metadata][ds_namespace]}
  }
}
